### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by z751** [omnirom/android_bootable_recovery#109]
Can we please have the ability to verify checksums of files using the built-in file manager of TWRP to make sure a flashable zip has been correctly downloaded and not corrupt?

Thanks.

**Comment by sndnvaps** [comment]
You can test it by youself. 
use md5sum or sha256sum

**Comment by z751** [comment]
Thank you.  I suppose I was just using the wrong command.  openssl and md5 command.
