### ISSUE TITLE
Getprop not working on after latest changes to 3.0.3 and toolbox problem

### ISSUE THREAD

**Issue by bhb27** [omnirom/android_bootable_recovery#116]
I'm building using cm-14.1 source and this recovery 7.1 branch.

# getprop
this particularly change
https://github.com/omnirom/android_bootable_recovery/commit/57332151129716bf6edf2792226ae4f1622fa93b#diff-5189683cc8a3b30ec721f80f97ebea32L220
changes the behavior of included or not getprop, then after that I can only use getprop if I mount system or use the system bin/sh tools with doesn't help when system is empty.

# toolbox (just a warning or help for others)
The problem is, that I need to build busybox because If I chose toolbox(i.e., TW_USE_TOOLBOX := true), some zip like anykernel2 that have building busybox and #bin/sh as a update-binary will fail to run some bin/sh test and can't be used to patch boot.img or wherever they do.

This Toolbox problem may also prevent some others zip that have a #bin/sh as a update-binary or use busybox from work, I only test for anykernel2..
anykernel2 link as reference
https://github.com/osm0sis/AnyKernel2
A if that fails is this
https://github.com/osm0sis/AnyKernel2/blob/master/tools/ak2-core.sh#L101
On BB TWRP that if will not enter, on Toolbox will and makes no sense...

The toolbox is more a warning then a problem, the main problem is none existent getprop/setprop...

**Comment by Lanchon** [comment]
FYI #121

**Comment by bhb27** [comment]
All good now
