### ISSUE TITLE
ota时ro.build.fingerprint检测问题

### ISSUE THREAD

**Issue by youyim123** [omnirom/android_bootable_recovery#138]
twrp进行ota时ro.build.fingerprint检测的是twrp里的default.prop，而不是system/build.prop里的。怎么让它默认检测system/build.prop。

**Comment by aboyboy** [comment]
good

**Comment by sndnvaps** [comment]
改twrp代码，修改其默认指向到system/build.prop
但当你system分区被fastboot wipe的时候，这个就不生效了。

**Comment by youyim123** [comment]
@sndnvaps 怎么默认指向到system/build.prop。我今天看了一晚上了，感觉应该改legacy_properties.h这个文件，但完全不知道怎么下手啊，第一次编译twrp，还不懂c语言。

**Comment by sndnvaps** [comment]
@youyim123 如果不懂 C和C++就可以不有说下去了。 因为需要自己分析代码的。

**Comment by youyim123** [comment]
ota问题已解决，再sbin里添加了一个脚本并删除default.prop里的ro.build.fingerprint @sndnvaps 

#!/sbin/sh`
mount /system
finger=$(cat /system/build.prop | grep "ro.build.fingerprint=" | dd bs=1 skip=21)
setprop ro.build.fingerprint $finger
mv /system/recovery-from-boot.bak /system/recovery-from-boot.p
umount /system
