### ISSUE TITLE
I:Unable to unlink '/data/...': No such file or directory

### ISSUE THREAD

**Issue by youyim123** [omnirom/android_bootable_recovery#139]
正在清除 Data 分区，跳过清除/data/media…
I:skipped '/data/lost+found'
I:skipped '/data/media'
I:Unable to unlink '/data/theme/current/description.xml': No such file or directory
I:Unable to unlink '/data/theme/current/preview/preview_icons_0.png': No such file or directory
I:Unable to unlink '/data/theme/current/preview/preview_launcher_0.png': No such file or directory
I:Unable to unlink '/data/theme/current/preview/preview_lockscreen_0.png': No such file or directory
I:Unable to unlink '/data/theme/current/preview/preview_thumbnail.png': No such file or directory
I:Unable to unlink '/data/theme/current/wallpaper/default_lock_wallpaper.png': No such file or directory
I:Unable to unlink '/data/theme/current/wallpaper/default_wallpaper.png': No such file or directory
I:Unable to unlink '/data/theme/current/fonts/description_font.xml': No such file or directory
I:Unable to unlink '/data/theme/current/fonts/preview/font_preview_contact.png': No such file or directory
I:Unable to unlink '/data/theme/current/fonts/preview/font_preview_launcher.png': No such file or directory
I:Unable to unlink '/data/theme/current/fonts/preview/font_preview_mms.png': No such file or directory
I:Unable to unlink '/data/theme/current/fonts/preview/font_preview_thumbnail.png': No such file or directory
I:Unable to unlink '/data/nubiaeffect/water_mark_drawable.argb': No such file or directory

**Comment by nkk71** [comment]
Fixed by 23853, issue can be closed.
