### ISSUE TITLE
Need help: I:Error writing destination fd (Invalid argument)

### ISSUE THREAD

**Issue by iamnotstanley** [omnirom/android_bootable_recovery#141]
I have a working, source-built TWRP for my device, but it has 1 issue. (TWRP 3.1.0, omnirom 5.1, 3.4.67 kernel, MT6582)
When I want flash or restore my boot or recovery partition (image) the TWRP throws out an error, but when I am installing a zip with a "package_extract_file ("path/to/the/image/file", "/dev/recovery");" or using the backup function it is working fully. I think I'll need to modify the TWRP source code, but I can't find the problematic part of the code. (Maybe [something near here](https://github.com/omnirom/android_bootable_recovery/blob/android-7.1/partition.cpp#L2325)?)
How can I fix it?
And what exactly does that 2 error message means?
"I:Error writing destination fd (Invalid argument)" this happens when I want to flash or restore an image
"ioctl(): blank: Invalid argument" this happens randomly
Please help, and thanks!
dmesg/kernel log: https://pastebin.com/raw/KRBYZW1D
recovery log: https://pastebin.com/raw/KJfswpSf
device tree: https://github.com/iamnotstanley/and..._huawei_h30u10

**Comment by Grace5921** [comment]
i have same issue on my xolo era4g (sc processor)

**Comment by iamnotstanley** [comment]
@Grace5921 Hey! I got some help about my problem, it can help to fix this for me and you if you have the exactly same issue. [https://forum.xda-developers.com/showpost.php?p=71993856&postcount=15](url)
