### ISSUE TITLE
TWRP 3.1.0 commandline help has invalid command "factoryreset"

### ISSUE THREAD

**Issue by pdsouza** [omnirom/android_bootable_recovery#146]
TWRP commandline mentions `factoryreset` as a command but it errors out as an unrecognized command.

```
 $ adb shell twrp help
TWRP openrecoveryscript command line tool, TWRP version 3.1.0-0

Allows command line usage of TWRP via openrecoveryscript commands.
Some common commands include:
  install /path/to/update.zip
  backup BSDC backupname
  restore backupname BSDC
  factoryreset
  wipe cache
  sideload
  set variable value
  get variable
  decrypt password
  remountrw

See more documentation at http://teamw.in/openrecoveryscript

$ adb shell twrp factoryreset
command is: 'factoryreset' and there is no value
E:Unrecognized script command: 'factoryreset'
Done processing script file

```

**Comment by martinbydefault** [comment]
The documentation was corrected in this commit: https://github.com/omnirom/android_bootable_recovery/commit/79605aece1fa5fbe6bed84ac88a61a58caa3545f#diff-4d5eff41b21fccc1000cb8a9610ce67c
The correct command to do factory reset is: `twrp wipe factoryreset` as you can see in here: 
https://github.com/omnirom/android_bootable_recovery/blob/007de98f69b1310f33a8baee008533b28d251cca/openrecoveryscript.cpp#L154

**Comment by pdsouza** [comment]
@martinbydefault Gotcha, thanks.
