### ISSUE TITLE
TWRP hangs, crashes and breaks ROM. Will not load TWRP until full format of the phone.

### ISSUE THREAD

**Issue by TheManWithTheGit** [omnirom/android_bootable_recovery#147]
So, I'm not too sure what is happening, but I'll go through what I'm doing.

I am using a Oneplus 3, that was originally running another custom ROM (marshmallow), and I wanted to update to sultan's LineageOS ROM(14.1).
Before updating to Lineage I didn't have this problem.

I used fastboot to wipe and reformat the: system, data, userdata, cache and recovery partitions.
I then flashed TWRP 3.1.0.0 to the recovery.
I then went into TWRP, and used the ADB sideload function in order to flash LineageOS.
I then flashed Open GApps, and then booted into LineageOS.
Once I set up the ROM, I could restart as much as I want, go into TWRP, with no problems.
I then encrypted the ROM using android's built in function, no problems.
From now on, if I load up TWRP, I will have about 10 seconds before TWRP locks up, and forces my phone to restart. This then breaks my ROM, and it makes it revert back to as if I just flashed the ROM (I.e: brings me back to the setup your account screen, everything works otherwise.)

I tried rolling back TWRP to 3.0.3.0, but still the same problem.
If I repeat reformatting the partitions using fastboot, no problems.

One thing that might be affecting it is that when I boot the phone, it has the old ROM boot splash until it loads the recovery or the ROM partway (I.e: for loading the ROM, it stays for a second or two)
Unless I'm missing something, the only thing I can see causing this problem is TWRP.

Sorry if I'm missing any information.

Edit: It seems that TWRP is now being weirder, after a certain amount of reboots unless I format the  whole phone again, it will not launch TWRP, and will break the ROM again.

If anyone knows how to completely wipe all the storage on the phone, that would be great, as I don't know how to do that exactly.

**Comment by aboyboy** [comment]
Good luck
