### ISSUE TITLE
ADB sideload doesn't work on, almost, all devices

### ISSUE THREAD

**Issue by Displax** [omnirom/android_bootable_recovery#160]
ADB sideload can't start on almost all devices.
TWRP ver. 3.1.0-0 and 3.1.1-0. On "grouper", for example.
Log: https://pastebin.com/NJr6fHc8

![screenshot_2017-05-20-14-57-00](https://cloud.githubusercontent.com/assets/16293419/26275607/2b0d9e5c-3d65-11e7-980f-6de14ce2f218.png)

**Comment by aykevl** [comment]
Works fine for me
