### ISSUE TITLE
Dalvik Wipe bug (TWRP 3.1.1-0)

### ISSUE THREAD

**Issue by Dark4Codrutz** [omnirom/android_bootable_recovery#164]
This is proven to be an issue on moto clark (so far only).
Whenever it tries to wipe dalivk cache the recovery itself crashes and the phone reboots back to system!

**Update1** : Reverting to 3.0.2 or 3.1.0 doesn't help. Also trying to manually delete **arm** or **arm64** folder inside /data/dalvik-cache causes the same reboot behavior.

**Update2** : Only possible workaround so far is renaming dalvik-cache folder, thus renabling flashing scripts to execute the wipe dalvik command without abruptly interrupting the update process!

**Comment by Jimzamjimmyy** [comment]
I am facing this same issue on OnePlus 2, but I haven't tried deleting the folder manually.

**Comment by Dark4Codrutz** [comment]
Sorry but I haven't updated this issue. The problem was laying in a "lazy" custom kernel that corrupted my data messing up some parts of the file system.
So this issue os closed from my point of view !

**Comment by shuboo786** [comment]
:grinning:
