### ISSUE TITLE
"Failed to parse int in" on OPP3 (Developer Preview 3)

### ISSUE THREAD

**Issue by Displax** [omnirom/android_bootable_recovery#165]
From updater-script:
`(!less_than_int(1496261382, getprop("ro.build.date.utc"))) || abort("E3003: Can't install this package (Wed May 31 20:09:42 UTC 2017) over newer build (" + getprop("ro.build.date") + ").");`

![screenshot_2017-06-09-19-22-26](https://user-images.githubusercontent.com/16293419/27003801-be0c27fc-4dfd-11e7-81f0-11a8233f8d3f.png)

**Comment by WinKarbik** [comment]
How you fix this?

**Comment by ItzLevvie** [comment]
@WinKarbik by wiping system partition and installing the desired .zip file
