### ISSUE TITLE
TWRP not updated for Samsug Galaxy S5 (klte)

### ISSUE THREAD

**Issue by kvsjxd** [omnirom/android_bootable_recovery#166]
Please update TWRP builds for Samsug Galaxy S5 (klte) to twrp-3.1.1-0. The last update was at version twrp-3.1.0-1.

**Comment by pix106** [comment]
This is TWRP repository, the device independant app, repository.
Devices have their maintainers, who build TWRP for their devices..
So ask the maintainer, not the orignial project owner :)

**Comment by kvsjxd** [comment]
👍
