### ISSUE TITLE
TWRP for devices msm8916 based on the Linux kernel 3.10.XX

### ISSUE THREAD

**Issue by SevenMaxs** [omnirom/android_bootable_recovery#18]
I recently bought myself Lenovo Vibe Z2 (K920) and immediately compiled TWRP 2.8.3.0.
But no matter what I did, in recovery mode only displays a splash picture Lenovo and adb works, everything. I can not even take off log.
The situation is similar to Lenovo Sisley (S90) and Samsung Galaxy A5 Duos (SM-A5000).
But this problem is not observed in HTC Desire 510 with kernel Linux 3.4.0.
Full source code for Lenovo Vibe Z2 http://download.lenovo.com/consumer/open_source_code/lenovo_vibe_z2_open_source.zip
How can I solve this problem?
Thank U!

**Comment by Dees-Troy** [comment]
This is not the place where we offer support for porting TWRP. The IRC channel, #twrp on Freenode is the best chance of getting help. Or at least maybe post in the compile guide on xda-developers.

**Comment by SevenMaxs** [comment]
Thank you, I understand.
