### ISSUE TITLE
Can't init, "default.xml not available"

### ISSUE THREAD

**Issue by clorophilla** [omnirom/android_bootable_recovery#184]
Guys, can someone give me an idea? I tried multiple times to run this:

`repo init -u https://github.com/omnirom/android_bootable_recovery.git -b android-7.1`

But in the end repo aborts stating: "fatal: manifest default.xml not available"

Am I missing something in order to sync the files?

**Comment by sndnvaps** [comment]
git clone https://github.com/omnirom/android_bootable_recovery.git -b android-7.1 .

**Comment by clorophilla** [comment]
Thanks a lot. I have the files, now to make TWRP for my phone. Hopefully I'll manage it.
