### ISSUE TITLE
MTP bug (solved)

### ISSUE THREAD

**Issue by russel5** [omnirom/android_bootable_recovery#20]
Hello, now when i compiling your recovery, MTP not working on my device at all.
On SDCard not copy, delete or other function
On Internal Storage copy to 99% then stop and nothing happend
When i compiling your recovery before you change MTP protocol and use TWAtomicInt https://github.com/omnirom/android_bootable_recovery/tree/3454ade92db48236057814f0ade5fa45bd57cd62 all works fine, without any issue
My device
Sony Z3 Compact
I use omni 5.0 source code for compiling
Please fix this, thanks.

UPD:
I found bug in code MtpStorage.cpp line 717
you are need this "while (i < len &&)" but you delete that thing and this is a big problem
while (i < len && inotify_thread_kill.get_value() == 0) {   <-- this is right!!!

**Comment by russel5** [comment]
If i use old tw_sys_atomics.h all works perfect

**Comment by IvvanVG** [comment]
Thank you!
