### ISSUE TITLE
i18n: major update of gui\theme\common\languages\fr.xml

### ISSUE THREAD

**Issue by Gozer-404** [omnirom/android_bootable_recovery#202]
* Added missing strings from `en.xml` (BTW some of the strings make `scripts/language_helper.py` complaining about nested comments - because some sentences contains `'--'`)
* Better translations and coherency with the android translations
* Corrected typos and grammatical errors
* A few translated strings were reduced (because too long to be displayed)

File available here:
[fr.xml.txt](https://github.com/omnirom/android_bootable_recovery/files/1616087/fr.xml.txt)

**Comment by Gozer-404** [comment]
Too bad, it seems that there is no interest in updates/corrections of the translations ?

**Comment by jerdog** [comment]
We have interest - however you need to use the proper process and use [Gerrit](https://gerrit.omnirom.org/) for submitting changes.
