### ISSUE TITLE
Gzip compress Error on TWRP 3.1.0

### ISSUE THREAD

**Issue by Zxilly** [omnirom/android_bootable_recovery#204]
I make the backup by `adb backup --twrp` and then swap my devices in order to upgrade to Android Oreo.Unfortunately,I couldn't restore from it. After that I upgrade TWRP to 3.2.0.However,it show the error `Incompatible adb backup version`.
I serach the issue and found #133 .I believe that I cannot restore my data with the latest release.However,there are some **very important** data in the backup.I wonder if exist any ways which could save my data.
# My Backup Data Was Created Under TWRP 3.1.0

**Comment by zxy1001** [comment]
Unfortunately,i enabled compress,if i could not find my data anymore?
