### ISSUE TITLE
[TWRP3.2.1.0][Android O]Failed to unmount '/system' 

### ISSUE THREAD

**Issue by youyim123** [omnirom/android_bootable_recovery#205]
I backup system after don't unmount it, and don't format it. until reboot recovery.
sorry my english is poor.
Android 8.1.0——failed
Android 7.1.1——succeed
备份system或者刷入一些会挂载system分区的刷机包，就会导致system无法卸载。如果不重启twrp就无法刷入ROM，格式化system。android7.1.1正常，android8.1.0不正常。
device tree：https://github.com/youyim123/android_device_nubia_nx563j-twrp
log：[recovery.log](https://github.com/omnirom/android_bootable_recovery/files/1702995/recovery.log)
[dmesg.log](https://github.com/omnirom/android_bootable_recovery/files/1703003/dmesg.log)
![screenshot_2018-02-07-06-02-12](https://user-images.githubusercontent.com/19865880/35916291-e00209b6-0c44-11e8-90aa-35b19face525.png)

**Comment by tletum13** [comment]
备份system或者刷入一些会挂载system分区的刷机包，就会导致system无法卸载。如果不重启twrp就无法刷入ROM，格式化system。android7.1.1正常，android8.1.0不正常。
device tree：

**Comment by HassanSardar** [comment]
Have you been able to find a solution for this?

**Comment by youyim123** [comment]
TW_NEVER_UNMOUNT_SYSTEM := true
@HassanSardar
