### ISSUE TITLE
TWRP app license - serious issue

### ISSUE THREAD

**Issue by gnunicode** [omnirom/android_bootable_recovery#206]
Distributing the app with the source code is not compatible with the GPL, which is the license of the rest of the work. From the TWRP app privacy policy:
![twrp](https://user-images.githubusercontent.com/34939282/36248053-0c0d41b2-122e-11e8-9537-a61d68ce11f2.png)

Although the pieces of software (TWRP recovery and TWRP app) would otherwise be separate, as building the source results in the app being pulled in the GPL considers them to be one work, which means that the termination conditions in the GPL come into force, so users do not have the legal right to use the TWRP recovery. (Disclaimer: I'm not a lawyer, but this issue still needs addressing). The most obvious solution is to add an exception to the GPL, but this does not fix the problem since the license terms of the app specifically forbid making it available to third parties, which distributing modified source code would do. Therefore the only options are to 1: remove the app, 2: change the license of the app or 3: to remove the GPL and replace it, say, with the Apache license. Option 2 would be the ideal option.

**Comment by jerdog** [comment]
Maybe @Dees-Troy  can respond?

**Comment by Dees-Troy** [comment]
Firstly, the apk that appears in the TWRP source is not the full app. It's a tiny shell that does almost nothing except popping a notification to the user asking them to install the full app. The apk is signed with the same key as the Play Store app which means that the Play Store should automatically update the app later on. If someone really wants the source code to this tiny apk, I don't care... it's not the full app and the tiny apk doesn't have the same privacy policy, agreements, etc.

There's projects using several licenses that are compiled into a TWRP ramdisk. TWRP's GPL license applies to the TWRP source code. The GPL license on the TWRP source code doesn't magically apply to everything else or override the licenses of the other projects that get included in the ramdisk. Similarly the GPLv2 kernel that is bundled into most recovery images doesn't make the entire recovery image GPLv2 or entire ROMs/firmwares GPLv2.
