### ISSUE TITLE
"fsflags=" flag doesn't work

### ISSUE THREAD

**Issue by Kostyan-nsk** [omnirom/android_bootable_recovery#21]
"fsflags=" flag doesn't work because in Process_FS_Flags function declaration was lost '&'.
Needs to change in partition.cpp and partitions.hpp from:
bool TWPartition::Process_FS_Flags(string& Options, int Flags)
to:
bool TWPartition::Process_FS_Flags(string& Options, int &Flags)

**Comment by bigbiff** [comment]
I believe that it's creating a local variable with the contents of Flags. Shouldn't need to have the &.

**Comment by Kostyan-nsk** [comment]
No, it's not.
Function parses string values of mount flags and returns their integer value into Mount_Flags property of TWPartition class (line #554 of partition.cpp) which uses further in mount() function calls.
For now mount flags are just lost inside of a function.

**Comment by Kostyan-nsk** [comment]
Finally, was fixed: https://github.com/omnirom/android_bootable_recovery/commit/bfb72b062a8e6e8bf83f9584101ceb092cf9d60d
