### ISSUE TITLE
Wish-List: GUI Terminal Keyboard apk for android

### ISSUE THREAD

**Issue by aIecxs** [omnirom/android_bootable_recovery#212]
I really would like to have the Terminal Keyboard as standalone app. is it generally possible porting it to android - how much work would it be? is there any Developer who know how to do it? can you point me to the respective file of source code?
is there any chance to see a TWRP-Keyboard.apk on Google Play Store in 2019 :-)

**Comment by DarrenRainey** [comment]
https://www.reddit.com/r/cyanogenmod/comments/546vyc/can_twrps_keyboard_ported_to_android/

From what I seen you would have to rewrite from source as TWRP doesn't use APKS.

However there are some good alternatives such as Hackers  keyboard
