### ISSUE TITLE
Commit 34ad728 causes TWRP on Xiaomi MIX 2S stuck in blank screen on boot

### ISSUE THREAD

**Issue by notsyncing** [omnirom/android_bootable_recovery#219]
- [ ] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [x] I am running the latest version of TWRP
- [x] I have read the FAQ (https://twrp.me/FAQ/)
- [x] I have searched for my issue and it does not already exist

**Device codename**: polaris
**TWRP version**: 3.2.1-0 git-34ad728

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
Compile TWRP with commit later than 34ad728

#### WHAT IS THE EXPECTED RESULT?
TWRP starts correctly.

#### WHAT HAPPENS INSTEAD?
Device just stuck in a blank screen with backlight on. adb works.

#### ADDITIONAL INFORMATION
Using my own device tree: https://github.com/notsyncing/android_device_xiaomi_polaris

I synced the latest twrp source code and found it just stuck in blank screen on boot. After some bisecting I found the commit 34ad728 is the cause.

`/tmp/recovery.log`: [recovery.log](https://github.com/omnirom/android_bootable_recovery/files/2041471/recovery.log)
`dmesg`: [dmesg.log](https://github.com/omnirom/android_bootable_recovery/files/2041484/dmesg.log)

**Comment by johmarjac** [comment]
Would you compile an unofficial build for us?

**Comment by simonsmh** [comment]
Of course revert works. Is there any compiling option to disable it?

**Comment by notsyncing** [comment]
According to the code, such an option does not exist. I guess it was because the `drm_page_flip_event` was triggered too quickly, even before reaching `flip_pending = true` at line 513, thus causing a dead loop on the next call to `drm_flip`. Tonight I'll take a try to set this flag before `drmModePageFlip` call and see if it works.

**Comment by notsyncing** [comment]
Tried, no luck, seems the DRM_MODE_PAGE_FLIP_EVENT does not being triggered at all. Now I have no idea why it stucks :(

**Comment by simonsmh** [comment]
https://github.com/omnirom/android_bootable_recovery/commit/25b850d6527b0da775fbcfb4910dccb0c3c09dbb
Reverted.
