### ISSUE TITLE
TWRP 3.2.2-0 breaks OTA updates on FP2

### ISSUE THREAD

**Issue by z3ntu** [omnirom/android_bootable_recovery#229]
- [x] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [x] I am running the latest version of TWRP
- [x] I have read the FAQ (https://twrp.me/FAQ/)
- [x] I have searched for my issue and it does not already exist

**Device codename**: FP2
**TWRP version**: 3.2.2-0

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
TWRP 3.2.2-0 doesn’t ask for the decryption password anymore when just installing OTA updates, now instead presenting the initial “Keep Read Only” prompt first, afterwards not doing the intended automatic install regardless of the user’s choice in this screen.
TWRP 3.2.1-0 worked in this case before, and still should (just needs confirmation now).

#### WHAT IS THE EXPECTED RESULT?
The OTA update applies

#### WHAT HAPPENS INSTEAD?
It doesn't get applied

#### ADDITIONAL INFORMATION
`/tmp/recovery.log`: https://paste.omnirom.org/view/d0991ad4
`dmesg`: https://paste.omnirom.org/view/e2fd6fc4

cc @AnotherElk

**Comment by NeatNit** [comment]
I reported this issue over here, it seems a fix is in the works:
https://github.com/TeamWin/Team-Win-Recovery-Project/issues/1273

**Comment by Diapolo** [comment]
I can also reproduce the issue on my FP2.

**Comment by z3ntu** [comment]
Should be fixed in version 3.2.3-0.
