### ISSUE TITLE
Mass storage does not work

### ISSUE THREAD

**Issue by IvvanVG** [omnirom/android_bootable_recovery#23]
When specifying "lun&d" in BoardConfig.mk, Mass storage mode mounted Internal storage (as CDRom without the ability to read or write) and external storage, this is not correct...
If I use "lun1" parameter, it can only be mounted active storage.
Device ZTE nubia Z7 mini.

Sorry for my English, translated via Google.

**Comment by sndnvaps** [comment]
建议看一看/tmp/recovery.log ，查看一下运行时，有什么错误信息。
不行，就用dmesg
