### ISSUE TITLE
android-9.0 branch cannot decrypt Android 8.1/9.0 FBE on Xiaomi MIX 2S

### ISSUE THREAD

**Issue by notsyncing** [omnirom/android_bootable_recovery#235]
- [ ] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [x] I am running the latest version of TWRP
- [x] I have read the FAQ (https://twrp.me/FAQ/)
- [x] I have searched for my issue and it does not already exist

**Device codename**: polaris
**TWRP version**: 3.2.3-0 android-9.0 branch git@007de98 with full omni-9.0 tree

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
Boot TWRP

#### WHAT IS THE EXPECTED RESULT?
Prompt for password and /data get decrypted

#### WHAT HAPPENS INSTEAD?
Stuck at TWRP splash page and logcat keeps giving:

```
06-18 13:37:01.925   629   629 D QSEECOMAPI: QSEECom_get_handle sb_length = 0xa000
06-18 13:37:01.925   629   629 D QSEECOMAPI: App is already loaded QSEE and app id = 1
06-18 13:37:01.928   629   629 E KeymasterUtils: TA API Major Version: 3
06-18 13:37:01.928   629   629 E KeymasterUtils: TA API Minor Version: 0
06-18 13:37:01.928   629   629 E KeymasterUtils: TA Major Version: 3
06-18 13:37:01.928   629   629 E KeymasterUtils: TA Minor Version: 130
06-18 13:37:01.933   629   629 E KeyMasterHalDevice: configure
06-18 13:37:01.933   629   629 E KeyMasterHalDevice: ret: 0
06-18 13:37:01.933   629   629 E KeyMasterHalDevice: resp->status: -40
06-18 13:37:01.933   629   629 F android.hardware.keymaster@4.0-impl: Configure failed
06-18 13:37:01.933   629   629 F libc    : Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 629 (android.hardwar), pid 629 (android.hardwar)
06-18 13:37:01.934   631   631 F libc    : exec failed: No such file or directory
06-18 13:37:01.935   629   629 F libc    : crash_dump helper failed to exec
06-18 13:37:02.009   537   537 W ServiceManagement: Waited one second for android.hardware.keymaster@4.0::IKeymasterDevice/default. Waiting another...
```

#### ADDITIONAL INFORMATION
I extracted keymaster 3.0 and 4.0 files `android.hardware.keymaster@4.0-service-qti` from stock MIUI, and the keymaster 4.0 could not start, giving above errors in logcat. I have no idea towards the `-40` error code, because I could not find it anywhere. Keymaster 3.0 can start but unable to decrypt, even on android 8.1 fbe.

Blobs are extracted from `miui_MIMIX2S_8.9.6_c615ab7bc9_9.0`.

Keymaster 3.0 gives following output:
```
06-03 01:04:23.923   570   570 D QSEECOMAPI: QSEECom_get_handle sb_length = 0xa000
06-03 01:04:23.923   570   570 D QSEECOMAPI: App is already loaded QSEE and app id = 1
06-03 01:04:23.924   571   571 D QSEECOMAPI: QSEECom_get_handle sb_length = 0xa000
06-03 01:04:23.927   571   571 D QSEECOMAPI: App is already loaded QSEE and app id = 1
06-03 01:04:23.927   570   570 E KeymasterUtils: TA API Major Version: 3
06-03 01:04:23.927   570   570 E KeymasterUtils: TA API Minor Version: 0
06-03 01:04:23.927   570   570 E KeymasterUtils: TA Major Version: 3
06-03 01:04:23.927   570   570 E KeymasterUtils: TA Minor Version: 121
06-03 01:04:23.933   571   571 E KeymasterUtils: TA API Major Version: 3
06-03 01:04:23.933   571   571 E KeymasterUtils: TA API Minor Version: 0
06-03 01:04:23.933   571   571 E KeymasterUtils: TA Major Version: 3
06-03 01:04:23.933   571   571 E KeymasterUtils: TA Minor Version: 121
06-03 01:04:23.934   570   570 I ServiceManagement: Removing namespace from process name android.hardware.keymaster@3.0-service-qti to keymaster@3.0-service-qti.
06-03 01:04:23.935   531   531 E SELinux : avc:  denied  { add } for interface=android.hardware.keymaster::IKeymasterDevice pid=570 scontext=u:r:recovery:s0 tcontext=u:object_r:hal_keymaster_hwservice:s0 tclass=hwservice_manager permissive=1
06-03 01:04:23.935   570   570 I android.hardware.keymaster@3.0-service: Registration complete for android.hardware.keymaster@3.0::IKeymasterDevice/default.
06-03 01:04:23.937   571   571 I ServiceManagement: Removing namespace from process name android.hardware.gatekeeper@1.0-service-qti to gatekeeper@1.0-service-qti.
06-03 01:04:23.937   531   531 E SELinux : avc:  denied  { add } for interface=android.hardware.gatekeeper::IGatekeeper pid=571 scontext=u:r:recovery:s0 tcontext=u:object_r:hal_gatekeeper_hwservice:s0 tclass=hwservice_manager permissive=1
06-03 01:04:23.937   571   571 I android.hardware.gatekeeper@1.0-service: Registration complete for android.hardware.gatekeeper@1.0::IGatekeeper/default.
06-03 01:04:23.969   536   536 E cutils-trace: Error opening trace file: No such file or directory (2)
06-03 01:04:23.976   531   531 W hwservicemanager: getTransport: Cannot find entry android.hidl.manager@1.0::IServiceManager/default in either framework or device manifest.
06-03 01:04:23.976   531   531 W hwservicemanager: getTransport: Cannot find entry android.hardware.keymaster@4.0::IKeymasterDevice/default in either framework or device manifest.
06-03 01:04:23.977   536   536 I /sbin/recovery: List of Keymaster HALs found:
06-03 01:04:23.977   536   536 I /sbin/recovery: Keymaster HAL #1: Keymaster HAL: 3 from QTI SecurityLevel: TRUSTED_ENVIRONMENT HAL: android.hardware.keymaster@3.0::IKeymasterDevice/default
06-03 01:04:23.981   570   570 E KeyMasterHalDevice: Begin send cmd failed
06-03 01:04:23.981   570   570 E KeyMasterHalDevice: ret: 0
06-03 01:04:23.981   570   570 E KeyMasterHalDevice: resp->status: -62
06-03 01:04:24.007   531   531 W hwservicemanager: getTransport: Cannot find entry android.hidl.manager@1.0::IServiceManager/default in either framework or device manifest.
06-03 01:04:24.008   531   531 W hwservicemanager: getTransport: Cannot find entry android.hardware.keymaster@4.0::IKeymasterDevice/default in either framework or device manifest.
06-03 01:04:24.009   536   536 I /sbin/recovery: List of Keymaster HALs found:
06-03 01:04:24.009   536   536 I /sbin/recovery: Keymaster HAL #1: Keymaster HAL: 3 from QTI SecurityLevel: TRUSTED_ENVIRONMENT HAL: android.hardware.keymaster@3.0::IKeymasterDevice/default
06-03 01:04:24.011   570   570 E KeyMasterHalDevice: Begin send cmd failed
06-03 01:04:24.011   570   570 E KeyMasterHalDevice: ret: 0
06-03 01:04:24.011   570   570 E KeyMasterHalDevice: resp->status: -62
06-03 01:04:24.029   531   531 W hwservicemanager: getTransport: Cannot find entry android.hidl.manager@1.0::IServiceManager/default in either framework or device manifest.
06-03 01:04:24.030   531   531 W hwservicemanager: getTransport: Cannot find entry android.hardware.keymaster@4.0::IKeymasterDevice/default in either framework or device manifest.
06-03 01:04:24.031   536   536 I /sbin/recovery: List of Keymaster HALs found:
06-03 01:04:24.031   536   536 I /sbin/recovery: Keymaster HAL #1: Keymaster HAL: 3 from QTI SecurityLevel: TRUSTED_ENVIRONMENT HAL: android.hardware.keymaster@3.0::IKeymasterDevice/default
06-03 01:04:24.033   570   570 E KeyMasterHalDevice: Begin send cmd failed
06-03 01:04:24.033   570   570 E KeyMasterHalDevice: ret: 0
06-03 01:04:24.033   570   570 E KeyMasterHalDevice: resp->status: -62
```

Tried on android 8.1 and 9.0 FBE, both gives the same result.

`/tmp/recovery.log` (keymaster 3.0 only):  https://paste.omnirom.org/view/95f4f19b
`dmesg`: (keymaster 3.0 only): https://paste.omnirom.org/view/d9b81af5

`/tmp/recovery.log` (keymaster 4.0 only):   https://paste.omnirom.org/view/54c5e2aa
`dmesg`: (keymaster 4.0 only): https://paste.omnirom.org/view/2762ff1a
`logcat`: (keymaster 4.0 only): https://paste.omnirom.org/view/bae79f6b

**Comment by cosmicdan** [comment]
Did you add a fileencryption= flag matching the device to your twrp fstab ?

**Comment by Mustang-ssc** [comment]
Were you able to verify that the "filenames_encryption_mode" for our polaris is "aes-256-cts"?
I am checking from our stock recovery based on Global Beta 8.9.13 and no definition is found on the recovery.img fstab.

According to Android documentation [https://source.android.com/security/encryption/file-based](url): "filenames_encryption_mode has two possible values: aes-256-cts and aes-256-heh. If filenames_encryption_mode is not specified then aes-256-cts value is used."

From my understanding seems the one you used is the correct one but not sure yet. I am currently making some tests but not yet able to perform this and confirm.

Did you try with "aes-256-heh" value? it would be as follows: `fileencryption=ice:aes-256-heh`

Lastly by checking on your fstab from your 9.0 device tree i don't see this flag set, i suppose that maybe you did not upload this changes yet but just to be sure in case was missed.

**Comment by bgcngm** [comment]
There's something funny going on. I have flashed P-based MIUI firmware and Lineage 16.0 and I see that data can be decrypted. It doesn't prompt for password because I didn't set one and it uses the default one. On the other hand, when I had the same TWRP version and Lineage 15.1 decryption was not working because the content of /sdcard appeared all scrambled.

**Comment by cosmicdan** [comment]
> There's something funny going on. I have flashed P-based MIUI firmware and Lineage 16.0 and I see that data can be decrypted. It doesn't prompt for password because I didn't set one and it uses the default one. On the other hand, when I had the same TWRP version and Lineage 15.1 decryption was not working because the content of /sdcard appeared all scrambled.

Yeah, I recall seeing multiple reports on various old device trees (that haven't been updated in months, likely because they haven't needed it) saying that FDE is no longer working in 8.1 or 9.0. All of the issues are dated recently - after the 9.0 FBE support was added in TWRP.

Maybe they/we will just have to settle for using TW_CRYPTO_USE_SYSTEM_VOLD.

**Comment by notsyncing** [comment]
@Mustang-ssc I determined the encryption mode in the same way as you described. I did not try `aes-256-heh` however. I'm planning to upgrade my device to Lineage 16 again sometime later, and I'll try it then.

**Comment by notsyncing** [comment]
@bgcngm Can we get the keymaster or qseecom error code details anywhere? They report error codes, and I googled hardly, but still could not find any explain towards them.

**Comment by cosmicdan** [comment]
FWIW, FBE decryption on the 9.0 branch of TWRP works fine on the Poco F1 - device is originally FDE though which TWRP cannot decrypt. I'm use ice rather than aes.

**Comment by macru** [comment]
> @bgcngm Can we get the keymaster or qseecom error code details anywhere? They report error codes, and I googled hardly, but still could not find any explain towards them.

@notsyncing I hope this helps you.
[https://android.googlesource.com/platform/hardware/interfaces/+/master/keymaster/3.0/types.hal](https://android.googlesource.com/platform/hardware/interfaces/+/master/keymaster/3.0/types.hal)

**Comment by notsyncing** [comment]
I saw twrp is still using codes in `KeyStorage4.cpp` to operate keymaster 3.0 if compiled with 9.0 tree. I'm wondering if this could be the reason? I tried forcing it to compile 3.0 keymaster things on 9.0 tree:

```makefile
#ifeq ($(shell test $(PLATFORM_SDK_VERSION) -ge 28; echo $$?),0)
        #9.0 rules
#        LOCAL_CFLAGS += -DUSE_KEYSTORAGE_4 -Wno-unused-variable -Wno-sign-compare -Wno-unused-parameter -Wno-comment
#        LOCAL_SRC_FILES += Ext4CryptPie.cpp Keymaster4.cpp KeyStorage4.cpp KeyUtil.cpp
#        LOCAL_SHARED_LIBRARIES += android.hardware.keymaster@4.0 libkeymaster4support
#        LOCAL_SHARED_LIBRARIES += android.hardware.gatekeeper@1.0 libkeystore_parcelables libkeystore_aidl
#        LOCAL_CFLAGS += -DHAVE_SYNTH_PWD_SUPPORT
#        LOCAL_SRC_FILES += Weaver1.cpp
#        LOCAL_SHARED_LIBRARIES += android.hardware.weaver@1.0
#        LOCAL_CFLAGS += -DHAVE_LIBKEYUTILS
#        LOCAL_SHARED_LIBRARIES += libkeyutils
#    else
        #8.0 rules
        LOCAL_CFLAGS += -DUSE_KEYSTORAGE_3
        LOCAL_SRC_FILES += Ext4Crypt.cpp Keymaster3.cpp KeyStorage3.cpp
        ifneq ($(wildcard hardware/interfaces/weaver/Android.bp),)
            #only present in some 8.0 trees and should be in all 8.1 trees
            LOCAL_CFLAGS += -DHAVE_SYNTH_PWD_SUPPORT
            LOCAL_SRC_FILES += Weaver1.cpp
            LOCAL_SHARED_LIBRARIES += android.hardware.weaver@1.0
        endif
        ifneq ($(wildcard system/core/libkeyutils/Android.bp),)
            #only present in some 8.0 trees and should be in all 8.1 trees
            LOCAL_CFLAGS += -DHAVE_LIBKEYUTILS
            LOCAL_SHARED_LIBRARIES += libkeyutils
        endif
#    endif
```

but could not get it compiled with many errors like `keystore/authorization_set.h` not found.

**Comment by mxalbert1996** [comment]
I found a TWRP image built by a Chinese developer (original thread [here](http://www.miui.com/thread-15271727-1-1.html)) which works on the latest MIUI and I have uploaded it to [Google Drive](https://drive.google.com/open?id=1YXJPQ1lns2_VI4rbSXszL2VJZtl_Y-oJ) if that helps.

**Comment by notsyncing** [comment]
@mxalbert1996 I tried and this recovery still cannot decrypt my 8.1 data encryption. Does this work for you on 9.0?

**Comment by mxalbert1996** [comment]
@notsyncing Yes. It works on my P-based MIUI (8.9.7 & 8.9.13).

**Comment by notsyncing** [comment]
Finally found the problem: the `init` in omni-9.0 is missing the `install_keyring` command.

I cannot submit to omni gerrit, so I attach the patch here:
[0001-init-Add-install_keyring-command.zip](https://github.com/omnirom/android_bootable_recovery/files/2410299/0001-init-Add-install_keyring-command.zip)

The gerrit always complains: 

```
error: remote unpack failed: error Missing tree aca0caeb41bab42998f80334bb82b098b6beced6
fatal: Unpack error, check server log
```

This is the recovery, if anyone wanted to try it: https://drive.google.com/open?id=1TUQOKqc36D97eCkn7CAF5mZosUoTjd4h

**Comment by notsyncing** [comment]
@bgcngm Sorry for the inconvenience, but I've changed the link. Please use https://drive.google.com/open?id=1lMLcapv1PfDgQMs63pogMYlwRmdLlcsc. It should not require any permission.

**Comment by Mustang-ssc** [comment]
Thanks for the discover @notsyncing .
I have tested it on my polaris with latest MIUI 8.9.20 China based on Pie and what still surprise is what @bgcngm mentioned: all data is decrypted by default without any prompt for the password/pattern i have set on ROM side.
Not directly related to this topic but good to mention though.
Anyway, this should not happen on non-MIUI ROMs/GSIs which is good.

**Comment by notsyncing** [comment]
I'm using Lineage 16.0 now, and on my device TWRP requires a password to decrypt data. You say MIUI did not require password even if you had set it? Then this should be a security issue.
