### ISSUE TITLE
The recovery screen displays as landscape, but the touch is portrait layout

### ISSUE THREAD

**Issue by gesangtome** [omnirom/android_bootable_recovery#248]
I'm happy that TWRP has been updated to 3.2.30, but I found a strange problem after compiling the test. The recovery interface displays as landscape screen, but the touch still appears as portrait screen. The TW_THEME landscape screen is switched, but it is invalid. I really need help now. I hope the official maintenance staff can see and provide some help, thank you very much!
Build with this device: https://github.com/Flowertome/android_device_teclast_m204g

**Comment by Skyrimus** [comment]
Use portrait theme for twrp

**Comment by Flowertome** [comment]
@Skyrimus 
I've tried the portrait theme, but it's still landscape. Now the best I can do is change the position of the touch to -180 degrees, which is the opposite of the screen. Is there any special way to reverse the display 180 degrees? Looking forward to your reply.

**Comment by Skyrimus** [comment]
Try boardconfig flag RECOVERY_TOUCHSCREEN_SWAP_XY := true

**Comment by Skyrimus** [comment]
And RECOVERY_TOUCHSCREEN_FLIP_Y := true or RECOVERY_TOUCHSCREEN_FLIP_X := true

**Comment by gesangtome** [comment]
@Skyrimus
