### ISSUE TITLE
Feature request: Password

### ISSUE THREAD

**Issue by TanyaEleventhGoddess** [omnirom/android_bootable_recovery#272]
In some devices fastboot can be locked down again, thus rendering the smartphone somewhat secure again (after setting a password in android of course)

Keeping TWRP installed in this case means a security hole, anyone can just boot in recovery and just do whatever he wants

This issue could be solved by saving a password somewhere in a file in the /data partition (I would advice against reusing /sdcard/TWRP/.twrps because it's readable by even unprivileged applications)

**Comment by MartinX3** [comment]
Your userdata is locked if encrypted

And keep in mind you should need to lock your bootloader and prevent any unlocking

**Comment by TanyaEleventhGoddess** [comment]
Fri, 16 Aug 2019 11:02:58 -0700 Martin Dünkelmann
<notifications@github.com>:
> Your userdata is locked if encrypted
> 
> And keep in mind you should need to lock your bootloader and prevent
> any unlocking
> 
Because of android messy encryption system (thanks Google for not
using legacy LUKS), encrypting the smartphone means having near-totally
no chance of recovering data if something goes wrong, even if you know
the password
Some devices allow to relock again the bootloader, as I said

**Comment by MartinX3** [comment]
But without decryption anyone can boot a twrp without password protection to grab your data.

And even if you are able to relock your bootloader, what does prevent relocking it again?

**Comment by TanyaEleventhGoddess** [comment]
Sat, 17 Aug 2019 06:36:13 -0700 Martin Dünkelmann
<notifications@github.com>:
> But without decryption anyone can boot a twrp without password
> protection to grab your data.
> 
> And even if you are able to relock your bootloader, what does prevent
> relocking it again?
> 
decryption -> encryption and relocking -> unlocking, you meant that?

If that's the case some bootloaders can't be unlocked from fastboot
without a method that proves you're the owner

Examples, xiaomi checks if the device is associated with your mi
account and oneplus won't permit fastboot unlock if it's disabled in
android developer settings

In these contexts the fact that TWRP doesn't have a password function
is the only vulnerability even if the phone is unencrypted

Well, there's also the possibility of desoldering phone memory but it's
not a thing everyone can do

**Comment by TanyaEleventhGoddess** [comment]
Sat, 17 Aug 2019 13:30:10 -0700 darkobas <notifications@github.com>:
> Closed #272.
> 
Wow, wonderful, closed with no reason

Now I understand why stock rom devs force to erase all your phone data
after unlock if recovery devs reject security features even after
they're suggested

**Comment by darkobas** [comment]
closed by mistake. its really wonderful to read this forum. i mean github

**Comment by Jasi2169** [comment]
this is important request and feature @Dees-Troy

**Comment by Dekamir** [comment]
Locking the phone while TWRP is flashed most of the time bricks the phone.

**Comment by Tomy0498** [comment]
Descargar recovery nuevo [android_bootable_recovery](https://github.com/omnirom/android_bootable_recovery/issues/272#issue-comment-box)

**Comment by SebiderSushi** [comment]
I support this request. It is useful on legacy, pre AVB devices where re-locking the booloader in fact still allows to boot custom ROMs and recoveries.
Google's reference implementation of the bootloader requires wiping all user data when moving from a locked bootloader to an unlocked state, and every major OEM should follow this recommendation.

There still remains the attack surface given by tools like Qualcomm EDL, Samsung's Odin and the likes, which can still be used to access data on the phone and replace ROM and Recovery with an unprotected version. But these tools are a little bit more device dependent and affect any such device regardless of its bootloader - be it OEM or TWRP. In effect, protecting TWRP with a passcode while re-locking the bootloader will at least take away a genric and very low-barrier attack surface on the device and, even disregarding anything else, would be about as secure as if the device were untampered with just OEM software present.

**Comment by SebiderSushi** [comment]
But keep in mind that TWRP developers are aware of the situation and the decision against this feature has already been made: https://twrp.me/faq/securetwrp.html

As it seems it would need at least a lot of convincing to see this feature impelented in upstream TWRP. Probably though, it will never happen.

You can also take a look at [OrangeFox Recovery](https://orangefox.tech).

**Comment by darkobas** [comment]
So close right? Right
