### ISSUE TITLE
Can I help to localize this in italian?

### ISSUE THREAD

**Issue by realtebo** [omnirom/android_bootable_recovery#28]
I'd like to help you, if it's an option, to localize the main gui into my language, italian. 
Is it possible?

**Comment by sndnvaps** [comment]
@realtebo you can fetch my project to do it .
i have make the twrp support multi language support.
 https://github.com/sndnvaps/android_bootable_recovery_twrp
i hope it can help you .

**Comment by realtebo** [comment]
Tell me if I'm in the right place before, please.

I ended into this repository from official TWRP page. I'd like to translate the recovery into italian. Do you think is it possible? Which files?

**Comment by sndnvaps** [comment]
@realtebo i think it was verry diffcult to merge you change into the official twrp 
1st. you can make you own branch , 
2nd. you can view my commit to figure it out  how to add multi language support 

my commit 
https://github.com/sndnvaps/android_bootable_recovery_twrp/commit/4566f851ae61cc5c1f94d613556e91be380b210a
https://github.com/sndnvaps/android_bootable_recovery_twrp/commit/2ad787d3d5d2167681e309b036263233d3e012e7

if you have any trouble ,you can email me .
