### ISSUE TITLE
permanent touchscreen calibration issue after installing twrp-tblte on trltexx

### ISSUE THREAD

**Issue by marius851000** [omnirom/android_bootable_recovery#284]
- [x] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [x] I am running the latest version of TWRP
- [x] I have read the FAQ (https://twrp.me/FAQ/)
- [x] I have searched for my issue and it does not already exist

**Device codename**: trltexx
**TWRP version**: 3.0.2.0

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
Take a trlteexx (samsung galaxy note 4)
install twrp v.3.3.1.0 for tblte
-- touchscreen and screen isn't well calibrated. Isn't too unexpected, as it isn't the good model.
install twrp v.3.0.2.0 for trltexx (latest available version)
-- touchscreen yet doesn't work in the same way that with tblte, but screen size is ok.
boot to the main OS.

#### WHAT IS THE EXPECTED RESULT?
Touchscreen is well calibrated.

#### WHAT HAPPENS INSTEAD?
 The touchscreen have the same problem than in twrp. The stylus work fine.

#### ADDITIONAL INFORMATION
As I have only flashed the RECOVERY partition, that mean that twrp made some permanent change related to touchscreen. I have done no other thing than reboot with twrp. 

I suppose the issue can be related to the different version of twrp, but I don't know how to compile an android system.

Update: I found the trltexx rom on 3.3.1.0. It doesn't solve the problem, however.
Update: factory reset & cache reset doesn't solve the problem.

**Comment by marius851000** [comment]
Solved this issue by dialing a special number allowing to update the firmware.

**Comment by JLCjlc** [comment]
what was the code that you dialed?
