### ISSUE TITLE
Mount bind error with Internal_SD Card (LG-D800)

### ISSUE THREAD

**Issue by blastagator** [omnirom/android_bootable_recovery#30]
Building with latest commits yields an error when changing partition type on /data partition.  When changing partition type, console outputs:

Formating Data using mkfs.f2fs...
E: mount -0 bind '/data/media' '/sdcard' process ended with error=255
E: mount -0 bind '/data/media' '/sdcard' process ended with error=255

My device (LG-G2) does not have an external memory card, so /data/media is the internal "sdcard".

I'm guessing this error was occuring before, and just not being outputted to the console (based on my review of this commit: https://github.com/omnirom/android_bootable_recovery/commit/2252d24c964df89189143e8d09626e9455e0f580

It doens't seem to be having any adverse effect.  Just scaring users.

Looks like someone has proposed a fix: https://gerrit.omnirom.org/#/c/13747/

**Comment by mionica** [comment]
Formatting succeeds; that "error" is expected as the "media" format (internal SD card) is not created by mkfs.f2fs
I guess it could be "fixed" by an mkdir media between mkfs and mount -o bind, but since this is purely cosmetic, I wouldn't worry about it anyway.

**Comment by blastagator** [comment]
I believe it also occured when going back to ext4.  Except instead of 2 errors, it outputted one.  I figured it was harmless, but also figured it would be relatively easy fix.  I haven't taken a dive into the twrp code.  Might have a look around and maybe do a pull request.

Thanks for fast response :)
