### ISSUE TITLE
exfat SD-card is not mounting after 23rd Dec commits

### ISSUE THREAD

**Issue by andreya108** [omnirom/android_bootable_recovery#50]
```
I:cmd: /sbin/exfat-fuse -o big_writes,max_read=131072,max_write=131072 /dev/block/mmcblk1 /external_sd
__bionic_open_tzdata: couldn't find any tzdata when looking for localtime!
__bionic_open_tzdata: couldn't find any tzdata when looking for GMT!
__bionic_open_tzdata: couldn't find any tzdata when looking for posixrules!
__bionic_open_tzdata: couldn't find any tzdata when looking for GMT!
__bionic_open_tzdata: couldn't find any tzdata when looking for posixrules!
ERROR: failed to get size of '/dev/block/mmcblk1'.
I:exfat-fuse failed to mount with result 'FUSE exfat 1.2.2
', trying vfat
I:Unable to mount '/external_sd'
```

**Comment by andreya108** [comment]
Built under omni 4.4

Googling reveals: https://groups.google.com/forum/m/#!msg/exfat/Iei35MqkRGk/UeGSjnbzgQsJ

**Comment by andreya108** [comment]
here is fix:
https://github.com/andreya108/android_bootable_recovery/commit/880453a6f885ccf228b43a46780fc14018ba3323

**Comment by andreya108** [comment]
and here is pull request: 
https://github.com/omnirom/android_bootable_recovery/pull/51

**Comment by sndnvaps** [comment]
you can push to review board. ..

**Comment by andreya108** [comment]
how to do it?

**Comment by sndnvaps** [comment]
cd  `<project>`
`<make edits>`
git add -A
git commit -m "commit message"
`git push ssh://<username>@gerrit.omnirom.org:29418/<project> HEAD:refs/for/android-6.0`

@andreya108

**Comment by andreya108** [comment]
thank you for a hint!
here is a review:
https://gerrit.omnirom.org/16394

**Comment by andreya108** [comment]
Fix merged! Closing the issue.
