### ISSUE TITLE
TWRP simulates screenshots.

### ISSUE THREAD

**Issue by easyaspi314** [omnirom/android_bootable_recovery#52]
Hello, I am using a SII Skyrocket on TWRP 2.8.7.0 modified only to allow using the virtual re-partitioning of the internal flash memory.
I noticed that when in Simulating Actions mode, you can't take screenshots with Power+Vol Dn, which in my opinion, is pointless, because isn't the idea behind that is so that you can safely do things and take screenshots of themes? It flashes the screen, logs that it saved the screenshot, but it is also simulated.

There is no real reason that you would need to simulate taking a screenshot. I spent a half an hour taking screenshots of how to virtual repartition my device, and nope, they didn't save.

This would be a logical enhancement.

**Comment by bigbiff** [comment]
In the code, I am not seeing the screenshot action wrapped by simulate. Can you try 3.0.2?

**Comment by easyaspi314** [comment]
Oh thanks for reminding me. 3.0.2 works. :smile:
