### ISSUE TITLE
System mounted ro in ORS

### ISSUE THREAD

**Issue by gossbill** [omnirom/android_bootable_recovery#70]
I think there's a bug in TWRP 3.0.2.0 when processing ORS scripts: the system partition is always mounted as ro, even though the TWRP settings specify rw.

Evidence:
Restoring the system partition manually works, so the partition must have been mounted as rw. This is as expected given that the option to make the system ro is not checked in the mount tab. See screenshot mount.png

When using ORS, the system gets mounted as ro and, therefore the restore process fails. This can be seen because mounting the system and then running the mount command shows the following: 
/dev/block/mmcblk0p23 on /system type ext4 (ro,seclabel,relatime,data=ordered)

Changing the mount to rw using a remount command doesn't help because [I believe] the restore process does its own mount of system.

I've attached the logs for the ORS restore, which includes the mount command, in recovery-ors.log

I've also attached the ORS file.
![mount](https://cloud.githubusercontent.com/assets/19230175/15084669/54766836-1418-11e6-835b-d8024eab4077.png)
[openrecoveryscript.txt](https://github.com/omnirom/android_bootable_recovery/files/252952/openrecoveryscript.txt)
[recovery-ors.log.txt](https://github.com/omnirom/android_bootable_recovery/files/252954/recovery-ors.log.txt)

**Comment by xiaolu** [comment]
@@ -305,6 +305,32 @@ int main(int argc, char **argv) {
 	if(crash_counter == 0)
 		TWFunc::Fixup_Time_On_Boot();
 
+#ifndef TW_OEM_BUILD
+	// Check if system has never been changed
+	TWPartition* sys = PartitionManager.Find_Partition_By_Path("/system");
+	TWPartition* ven = PartitionManager.Find_Partition_By_Path("/vendor");
+	if (sys) {
+		if ((DataManager::GetIntValue("tw_mount_system_ro") == 0 && sys->Check_Lifetime_Writes() == 0) || DataManager::GetIntValue("tw_mount_system_ro") == 2) {
+			if (DataManager::GetIntValue("tw_never_show_system_ro_page") == 0) {
+				DataManager::SetValue("tw_back", "main");
+				if (gui_startPage("system_readonly", 1, 1) != 0) {
+					LOGERR("Failed to start system_readonly GUI page.\n");
+				}
+			} else if (DataManager::GetIntValue("tw_mount_system_ro") == 0) {
+				sys->Change_Mount_Read_Only(false);
+				if (ven)
+					ven->Change_Mount_Read_Only(false);
+			}
+		} else if (DataManager::GetIntValue("tw_mount_system_ro") == 1) {
+			// Do nothing, user selected to leave system read only
+		} else {
+			sys->Change_Mount_Read_Only(false);
+			if (ven)
+				ven->Change_Mount_Read_Only(false);
+		}
+	}
+#endif
+
 	// Run any outstanding OpenRecoveryScript
 	if (DataManager::GetIntValue(TW_IS_ENCRYPTED) == 0 && (TWFunc::Path_Exists(SCRIPT_FILE_TMP) || TWFunc::Path_Exists(SCRIPT_FILE_CACHE))) {
 		OpenRecoveryScript::Run_OpenRecoveryScript();
@@ -335,31 +361,6 @@ int main(int argc, char **argv) {
 	PartitionManager.Disable_MTP();
 #endif
 
-#ifndef TW_OEM_BUILD
-	// Check if system has never been changed
-	TWPartition* sys = PartitionManager.Find_Partition_By_Path("/system");
-	TWPartition* ven = PartitionManager.Find_Partition_By_Path("/vendor");
-	if (sys) {
-		if ((DataManager::GetIntValue("tw_mount_system_ro") == 0 && sys->Check_Lifetime_Writes() == 0) || DataManager::GetIntValue("tw_mount_system_ro") == 2) {
-			if (DataManager::GetIntValue("tw_never_show_system_ro_page") == 0) {
-				DataManager::SetValue("tw_back", "main");
-				if (gui_startPage("system_readonly", 1, 1) != 0) {
-					LOGERR("Failed to start system_readonly GUI page.\n");
-				}
-			} else if (DataManager::GetIntValue("tw_mount_system_ro") == 0) {
-				sys->Change_Mount_Read_Only(false);
-				if (ven)
-					ven->Change_Mount_Read_Only(false);
-			}
-		} else if (DataManager::GetIntValue("tw_mount_system_ro") == 1) {
-			// Do nothing, user selected to leave system read only
-		} else {
-			sys->Change_Mount_Read_Only(false);
-			if (ven)
-				ven->Change_Mount_Read_Only(false);
-		}
-	}
-#endif
 	// Launch the main GUI
 	gui_start();

**Comment by xiaolu** [comment]
http://pastebin.com/PVFbhRDX

**Comment by gossbill** [comment]
I've recently (December 2018) found out that the remountrw command (https://twrp.me/faq/openrecoveryscript.html), if executed before the restore command, will mount the system partition as read-write and the restore command will run successfully.
I tested this on version 3.2.3-0 of TWRP in my OnePlus 3T.
I'm, therefore, closing this issue.

**Comment by gossbill** [comment]
I've recently (December 2018) found out that the remountrw command (https://twrp.me/faq/openrecoveryscript.html), if executed before the restore command, will mount the system partition as read-write and the restore command will run successfully.
I tested this on version 3.2.3-0 of TWRP in my OnePlus 3T.
I'm, therefore, closing this issue.
