### ISSUE TITLE
cm13.0 now requires gr_set_font(); in minui.h header file

### ISSUE THREAD

**Issue by discipuloosho** [omnirom/android_bootable_recovery#84]
Building cm13.0 with TWRP now requires `void gr_set_font(const char* name);` in minui.h, if not, built fail with undefined reference compile error.
https://github.com/CyanogenMod/android_vendor_cm/blob/cm-13.0/charger/healthd_board_cm.cpp#L335

______EDIT______
The principal commit says: 

>  "cm: charger: Add support for double backlight displays" https://github.com/CyanogenMod/android_vendor_cm/commit/cadd0be0896dcf4af2b263350261cfa9dc98c7da

So, I do not know if that has something to do about shamu (Nexus 6). Does shamu double backlight display? I know nothing about all this. I delete line code for now .. cm13.0 build end.
Thanks in advance for TWRP , it is very useful .

**Comment by DevUt** [comment]
I think as minui exists for aosp twrp should add minuicm for cm compatibility

**Comment by rugk** [comment]
With this issue being closed in so many forks of this project why was not it closed in the main/official repo here?

**Comment by DevUt** [comment]
@rugk it would be done

**Comment by discipuloosho** [comment]
Now, the goal is adapt it for cm-14.1 (lineageos cm-14.1)
