### ISSUE TITLE
Clean up PartitionSettings (commit Sept 14 2016)

### ISSUE THREAD

**Issue by shoey63** [omnirom/android_bootable_recovery#91]
This breaks image flashing with the message "Error opening: 'external_sd/<name>.img/' (Not a directory)". It appears twice in a row.
![screenshot_2016-09-18-19-55-35](https://cloud.githubusercontent.com/assets/6688602/18615669/12fecba6-7ddf-11e6-8155-58ed79aa6f86.png)

git revert dcf2b674c4c2eb1631ebc76e3606c1c7691321a8
and it works again.

**Comment by wzsx150** [comment]
me, too

**Comment by shoey63** [comment]
This (not merged yet) commit fixes the issue [https://gerrit.omnirom.org/#/c/19248/](url)
